org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.home=C:/Users/opale/AppData/Local/Programs/IntelliJ IDEA/jbr

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.19
fabric_api_version=0.149.0+26.2

mod_version=26.2-26.A
maven_group=com.cookiecraftmods.builderspalette
archives_base_name=builders_palette
