org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.workers.max=1
org.gradle.caching=true
org.gradle.java.home=C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2025.2\\jbr

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.244
loader_version_range=[2,)

mod_version=26.A
mod_group_id=com.cookiecraftmods.builderspalette
archives_base_name=builders_palette
mod_id=builders_palette
mod_name=Builder's Palette
mod_license=CookiecraftMods Licence v1.0
mod_authors=opaleq - cookiecraft mods
mod_description=Building blocks, palettes, and decorative materials.
