org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.workers.max=1
org.gradle.caching=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.80

mod_version=26.1.2-26.A
mod_group_id=com.cookiecraftmods.builderspalette
archives_base_name=builders_palette
mod_id=builders_palette
mod_name=Builder's Palette
mod_license=CookiecraftMods Licence v1.0
mod_authors=opaleq - cookiecraft mods
mod_description=Building blocks, palettes, and decorative materials.
