
package com.cookiecraftmods.builderspalette.init;

import com.cookiecraftmods.builderspalette.init.RegistryObject;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.Block;
import java.util.function.Supplier;

public class BuildersPaletteModTabs {
	public static void register() {
	}

	private static RegistryObject<CreativeModeTab> register(String name, Supplier<? extends CreativeModeTab> supplier) {
		return RegistryObject.register(BuiltInRegistries.CREATIVE_MODE_TAB, name, supplier);
	}

	public static final RegistryObject<CreativeModeTab> BUILDERS_PALETTE = register("builders_palette",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.builders_palette.builders_palette")).icon(() -> new ItemStack(BuildersPaletteModBlocks.WHITE_VERTICAL_POT.get())).displayItems((parameters, tabData) -> {
				tabData.accept(BuildersPaletteModBlocks.BRICKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BRICKS_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BRICKS_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BRICKS_WALL.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.CRACKED_BRICKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.CRACKED_BRICKS_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.CRACKED_BRICKS_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.CRACKED_BRICKS_WALL.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLACK_BRICKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLACK_BRICKS_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLACK_BRICKS_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLACK_BRICKS_WALL.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREY_BRICKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREY_BRICKS_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREY_BRICKS_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREY_BRICKS_WALL.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_BRICKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_BRICKS_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_BRICKS_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_BRICKS_WALL.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.PEACH_BRICKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.PEACH_BRICKS_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.PEACH_BRICKS_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.PEACH_BRICKS_WALL.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DARK_GREY_BRICKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DARK_GREY_BRICKS_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DARK_GREY_BRICKS_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DARK_GREY_BRICKS_WALL.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BROWN_BRICKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BROWN_BRICKS_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BROWN_BRICKS_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BROWN_BRICKS_WALL.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_BROWN_BRICKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_BROWN_BRICKS_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_BROWN_BRICKS_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_BROWN_BRICKS_WALL.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLUE_BRICKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLUE_BRICKS_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLUE_BRICKS_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLUE_BRICKS_WALL.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREEN_BRICKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREEN_BRICKS_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREEN_BRICKS_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREEN_BRICKS_WALL.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_GRAY_BRICKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_GRAY_BRICKS_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_GRAY_BRICKS_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_GRAY_BRICKS_WALL.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLACK_N_WHITE_TILES.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLACK_N_WHITE_TILES_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLACK_N_WHITE_TILES_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLACK_TILES.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLACK_TILES_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLACK_TILES_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_TILES.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_TILES_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_TILES_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.SMOOTH_BRICKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_SMOOTH_BRICKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLACK_SMOOTH_BRICKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DARK_RED_BRICKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.RED_PAVEMENT.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.RED_PAVEMENT_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.RED_PAVEMENT_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREY_PAVEMENT.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREY_PAVEMENT_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREY_PAVEMENT_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_PAVEMENT.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_PAVEMENT_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_PAVEMENT_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_OAK_WOOD.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_OAK_LOG.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_OAK_PLANKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_OAK_LEAVES.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_OAK_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_OAK_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_OAK_FENCE.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_OAK_FENCE_GATE.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_OAK_PRESSURE_PLATE.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_OAK_BUTTON.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DARK_RED_WOOD.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DARK_RED_LOG.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DARK_RED_PLANKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DARK_RED_LEAVES.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DARK_RED_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DARK_RED_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DARK_RED_FENCE.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DARK_RED_FENCE_GATE.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DARK_RED_PRESSURE_PLATE.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DARK_RED_BUTTON.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREY_WOOD.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREY_LOG.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREY_PLANKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREY_LEAVES.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREY_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREY_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREY_FENCE.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREY_FENCE_GATE.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREY_PRESSURE_PLATE.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREY_BUTTON.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_WOOD.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_LOG.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_PLANKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_LEAVES.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_FENCE.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_FENCE_GATE.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_PRESSURE_PLATE.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_BUTTON.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WENGE_WOOD.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WENGE_LOG.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WENGE_PLANKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WENGE_LEAVES.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WENGE_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WENGE_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WENGE_FENCE.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WENGE_FENCE_GATE.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WENGE_PRESSURE_PLATE.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WENGE_BUTTON.get().asItem());
				acceptBlocks(tabData,
					BuildersPaletteModBlocks.MAPLE_WOOD,
					BuildersPaletteModBlocks.MAPLE_LOG,
					BuildersPaletteModBlocks.MAPLE_PLANKS,
					BuildersPaletteModBlocks.MAPLE_LEAVES,
					BuildersPaletteModBlocks.MAPLE_STAIRS,
					BuildersPaletteModBlocks.MAPLE_SLAB,
					BuildersPaletteModBlocks.MAPLE_FENCE,
					BuildersPaletteModBlocks.MAPLE_FENCE_GATE,
					BuildersPaletteModBlocks.MAPLE_PRESSURE_PLATE,
					BuildersPaletteModBlocks.MAPLE_BUTTON);
				acceptBlocks(tabData,
					BuildersPaletteModBlocks.CEDAR_WOOD,
					BuildersPaletteModBlocks.CEDAR_LOG,
					BuildersPaletteModBlocks.CEDAR_PLANKS,
					BuildersPaletteModBlocks.CEDAR_LEAVES,
					BuildersPaletteModBlocks.CEDAR_STAIRS,
					BuildersPaletteModBlocks.CEDAR_SLAB,
					BuildersPaletteModBlocks.CEDAR_FENCE,
					BuildersPaletteModBlocks.CEDAR_FENCE_GATE,
					BuildersPaletteModBlocks.CEDAR_PRESSURE_PLATE,
					BuildersPaletteModBlocks.CEDAR_BUTTON);
				acceptBlocks(tabData,
					BuildersPaletteModBlocks.WALNUT_WOOD,
					BuildersPaletteModBlocks.WALNUT_LOG,
					BuildersPaletteModBlocks.WALNUT_PLANKS,
					BuildersPaletteModBlocks.WALNUT_LEAVES,
					BuildersPaletteModBlocks.WALNUT_STAIRS,
					BuildersPaletteModBlocks.WALNUT_SLAB,
					BuildersPaletteModBlocks.WALNUT_FENCE,
					BuildersPaletteModBlocks.WALNUT_FENCE_GATE,
					BuildersPaletteModBlocks.WALNUT_PRESSURE_PLATE,
					BuildersPaletteModBlocks.WALNUT_BUTTON);
				acceptBlocks(tabData,
					BuildersPaletteModBlocks.OLIVE_WOOD,
					BuildersPaletteModBlocks.OLIVE_LOG,
					BuildersPaletteModBlocks.OLIVE_PLANKS,
					BuildersPaletteModBlocks.OLIVE_LEAVES,
					BuildersPaletteModBlocks.OLIVE_STAIRS,
					BuildersPaletteModBlocks.OLIVE_SLAB,
					BuildersPaletteModBlocks.OLIVE_FENCE,
					BuildersPaletteModBlocks.OLIVE_FENCE_GATE,
					BuildersPaletteModBlocks.OLIVE_PRESSURE_PLATE,
					BuildersPaletteModBlocks.OLIVE_BUTTON);
				acceptBlocks(tabData,
					BuildersPaletteModBlocks.PURPLEHEART_WOOD,
					BuildersPaletteModBlocks.PURPLEHEART_LOG,
					BuildersPaletteModBlocks.PURPLEHEART_PLANKS,
					BuildersPaletteModBlocks.PURPLEHEART_LEAVES,
					BuildersPaletteModBlocks.PURPLEHEART_STAIRS,
					BuildersPaletteModBlocks.PURPLEHEART_SLAB,
					BuildersPaletteModBlocks.PURPLEHEART_FENCE,
					BuildersPaletteModBlocks.PURPLEHEART_FENCE_GATE,
					BuildersPaletteModBlocks.PURPLEHEART_PRESSURE_PLATE,
					BuildersPaletteModBlocks.PURPLEHEART_BUTTON);
				tabData.accept(BuildersPaletteModBlocks.BLACK_SMOOTH_TERRACOTTA.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLACK_SMOOTH_TERRACOTTA_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLACK_SMOOTH_TERRACOTTA_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DARK_GRAY_SMOOTH_TERRACOTTA.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DARK_GRAY_SMOOTH_TERRACOTTA_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DARK_GRAY_SMOOTH_TERRACOTTA_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GRAY_SMOOTH_TERRACOTTA.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GRAY_SMOOTH_TERRACOTTA_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GRAY_SMOOTH_TERRACOTTA_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_GRAY_SMOOTH_TERRACOTTA.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_GRAY_SMOOTH_TERRACOTTA_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_GRAY_SMOOTH_TERRACOTTA_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_SMOOTH_TERRACOTTA.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_SMOOTH_TERRACOTTA_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_SMOOTH_TERRACOTTA_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.RED_SMOOTH_TERRACOTTA.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.RED_SMOOTH_TERRACOTTA_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.RED_SMOOTH_TERRACOTTA_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREEN_SMOOTH_TERRACOTTA.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREEN_SMOOTH_TERRACOTTA_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREEN_SMOOTH_TERRACOTTA_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLUE_SMOOTH_TERRACOTTA.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLUE_SMOOTH_TERRACOTTA_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLUE_SMOOTH_TERRACOTTA_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.YELLOW_SMOOTH_TERRACOTTA.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.YELLOW_SMOOTH_TERRACOTTA_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.YELLOW_SMOOTH_TERRACOTTA_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.ORANGE_SMOOTH_TERRACOTTA.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.ORANGE_SMOOTH_TERRACOTTA_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.ORANGE_SMOOTH_TERRACOTTA_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.PINK_SMOOTH_TERRACOTTA.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.PINK_SMOOTH_TERRACOTTA_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.PINK_SMOOTH_TERRACOTTA_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.PURPLE_SMOOTH_TERRACOTTA.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.PURPLE_SMOOTH_TERRACOTTA_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.PURPLE_SMOOTH_TERRACOTTA_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.ASPHALT_BLOCK.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.ASPHALT_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.ASPHALT_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DASHED_LINE_ASPHALT.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DOUBLE_CONTINUOUS_LINE_ASPHALT.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.CONTINUOUS_LINED_ASPHALT.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.YIELD_ASPHALT.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WIDE_DASHED_LINED_ASPHALT.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.ZEBRAASPHALT.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.SHORT_DASHED_LINED_ASPHALT.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DEEP_BLUE_TILES.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DEEP_SCARLETT_TILES.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.LIGHT_BLUE_TILES.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_VERTICAL_POT.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.BLACK_3D_BRICKS.get().asItem());
				tabData.accept(BuildersPaletteModItems.BLACK_BRICK.get());
				tabData.accept(BuildersPaletteModBlocks.WHITE_3D_BRICKS.get().asItem());
				tabData.accept(BuildersPaletteModItems.WHITE_BRICK.get());
				tabData.accept(BuildersPaletteModBlocks.RED_3D_BRICKS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.COFFE_WOOD_WALL_SLATS.get().asItem());
				// BEGIN GENERATED WOOD WALL SLATS
				tabData.accept(BuildersPaletteModBlocks.LIGHT_OAK_LOG_WALL_SLATS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.DARK_RED_LOG_WALL_SLATS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.GREY_LOG_WALL_SLATS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_LOG_WALL_SLATS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WENGE_LOG_WALL_SLATS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.MAPLE_LOG_WALL_SLATS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.CEDAR_LOG_WALL_SLATS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WALNUT_LOG_WALL_SLATS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.OLIVE_LOG_WALL_SLATS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.PURPLEHEART_LOG_WALL_SLATS.get().asItem());
				// END GENERATED WOOD WALL SLATS
				tabData.accept(BuildersPaletteModBlocks.FRAMED_GLASS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_WALL_PANELS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.CORNER_WHITE_WALL_PANELS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.WHITE_CONCRETE.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.PACKED_MUD_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.PACKED_MUD_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.PACKED_MUD_WALL.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.CALCITE_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.CALCITE_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.CALCITE_WALL.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.TUFF_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.TUFF_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.TUFF_WALL.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.END_STONE_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.END_STONE_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.END_STONE_WALL.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.TERRACOTTA_STAIRS.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.TERRACOTTA_SLAB.get().asItem());
				tabData.accept(BuildersPaletteModBlocks.TERRACOTTA_WALL.get().asItem());
				acceptBlocks(tabData,
					BuildersPaletteModBlocks.WHITE_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.WHITE_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.WHITE_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.ORANGE_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.ORANGE_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.ORANGE_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.MAGENTA_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.MAGENTA_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.MAGENTA_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.LIGHT_BLUE_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.LIGHT_BLUE_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.LIGHT_BLUE_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.YELLOW_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.YELLOW_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.YELLOW_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.LIME_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.LIME_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.LIME_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.PINK_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.PINK_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.PINK_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.GRAY_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.GRAY_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.GRAY_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.LIGHT_GRAY_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.LIGHT_GRAY_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.LIGHT_GRAY_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.CYAN_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.CYAN_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.CYAN_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.PURPLE_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.PURPLE_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.PURPLE_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.BLUE_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.BLUE_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.BLUE_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.BROWN_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.BROWN_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.BROWN_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.GREEN_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.GREEN_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.GREEN_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.RED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.RED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.RED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.BLACK_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.BLACK_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.BLACK_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.WHITE_GLAZED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.WHITE_GLAZED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.WHITE_GLAZED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.ORANGE_GLAZED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.ORANGE_GLAZED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.ORANGE_GLAZED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.MAGENTA_GLAZED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.MAGENTA_GLAZED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.MAGENTA_GLAZED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.YELLOW_GLAZED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.YELLOW_GLAZED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.YELLOW_GLAZED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.LIME_GLAZED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.LIME_GLAZED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.LIME_GLAZED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.PINK_GLAZED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.PINK_GLAZED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.PINK_GLAZED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.GRAY_GLAZED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.GRAY_GLAZED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.GRAY_GLAZED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.CYAN_GLAZED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.CYAN_GLAZED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.CYAN_GLAZED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.PURPLE_GLAZED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.PURPLE_GLAZED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.PURPLE_GLAZED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.BLUE_GLAZED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.BLUE_GLAZED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.BLUE_GLAZED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.BROWN_GLAZED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.BROWN_GLAZED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.BROWN_GLAZED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.GREEN_GLAZED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.GREEN_GLAZED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.GREEN_GLAZED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.RED_GLAZED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.RED_GLAZED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.RED_GLAZED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.BLACK_GLAZED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.BLACK_GLAZED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.BLACK_GLAZED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.ETCHED_TUFF_TILES,
					BuildersPaletteModBlocks.ETCHED_TUFF_TILES_STAIRS,
					BuildersPaletteModBlocks.ETCHED_TUFF_TILES_SLAB,
					BuildersPaletteModBlocks.ETCHED_TUFF_TILES_WALL,
					BuildersPaletteModBlocks.SPIRAL_TUFF_TILES,
					BuildersPaletteModBlocks.SPIRAL_TUFF_TILES_STAIRS,
					BuildersPaletteModBlocks.SPIRAL_TUFF_TILES_SLAB,
					BuildersPaletteModBlocks.SPIRAL_TUFF_TILES_WALL,
					BuildersPaletteModBlocks.WOVEN_TUFF_TILES,
					BuildersPaletteModBlocks.WOVEN_TUFF_TILES_STAIRS,
					BuildersPaletteModBlocks.WOVEN_TUFF_TILES_SLAB,
					BuildersPaletteModBlocks.WOVEN_TUFF_TILES_WALL,
					BuildersPaletteModBlocks.FRAMED_TUFF_TILES,
					BuildersPaletteModBlocks.FRAMED_TUFF_TILES_STAIRS,
					BuildersPaletteModBlocks.FRAMED_TUFF_TILES_SLAB,
					BuildersPaletteModBlocks.FRAMED_TUFF_TILES_WALL,
					BuildersPaletteModBlocks.WEATHERED_TUFF_TILES,
					BuildersPaletteModBlocks.WEATHERED_TUFF_TILES_STAIRS,
					BuildersPaletteModBlocks.WEATHERED_TUFF_TILES_SLAB,
					BuildersPaletteModBlocks.WEATHERED_TUFF_TILES_WALL,
					BuildersPaletteModBlocks.TUFF_TILE_BRICKS,
					BuildersPaletteModBlocks.TUFF_TILE_BRICKS_STAIRS,
					BuildersPaletteModBlocks.TUFF_TILE_BRICKS_SLAB,
					BuildersPaletteModBlocks.TUFF_TILE_BRICKS_WALL,
					BuildersPaletteModBlocks.CALCITE_BRICKS,
					BuildersPaletteModBlocks.CALCITE_BRICKS_STAIRS,
					BuildersPaletteModBlocks.CALCITE_BRICKS_SLAB,
					BuildersPaletteModBlocks.CALCITE_BRICKS_WALL,
					BuildersPaletteModBlocks.TUFF_BRICKS,
					BuildersPaletteModBlocks.TUFF_BRICKS_STAIRS,
					BuildersPaletteModBlocks.TUFF_BRICKS_SLAB,
					BuildersPaletteModBlocks.TUFF_BRICKS_WALL,
					BuildersPaletteModBlocks.DIORITE_BRICKS,
					BuildersPaletteModBlocks.DIORITE_BRICKS_STAIRS,
					BuildersPaletteModBlocks.DIORITE_BRICKS_SLAB,
					BuildersPaletteModBlocks.DIORITE_BRICKS_WALL,
					BuildersPaletteModBlocks.GRANITE_BRICKS,
					BuildersPaletteModBlocks.GRANITE_BRICKS_STAIRS,
					BuildersPaletteModBlocks.GRANITE_BRICKS_SLAB,
					BuildersPaletteModBlocks.GRANITE_BRICKS_WALL,
					BuildersPaletteModBlocks.ANDESITE_BRICKS,
					BuildersPaletteModBlocks.ANDESITE_BRICKS_STAIRS,
					BuildersPaletteModBlocks.ANDESITE_BRICKS_SLAB,
					BuildersPaletteModBlocks.ANDESITE_BRICKS_WALL,
					BuildersPaletteModBlocks.SANDSTONE_BRICKS,
					BuildersPaletteModBlocks.SANDSTONE_BRICKS_STAIRS,
					BuildersPaletteModBlocks.SANDSTONE_BRICKS_SLAB,
					BuildersPaletteModBlocks.SANDSTONE_BRICKS_WALL,
					BuildersPaletteModBlocks.RED_SANDSTONE_BRICKS,
					BuildersPaletteModBlocks.RED_SANDSTONE_BRICKS_STAIRS,
					BuildersPaletteModBlocks.RED_SANDSTONE_BRICKS_SLAB,
					BuildersPaletteModBlocks.RED_SANDSTONE_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.PACKED_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_BLACK_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.PACKED_BLACK_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_BLACK_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_BLACK_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_RED_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.PACKED_RED_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_RED_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_RED_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_GREEN_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.PACKED_GREEN_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_GREEN_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_GREEN_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_BROWN_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.PACKED_BROWN_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_BROWN_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_BROWN_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_BLUE_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.PACKED_BLUE_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_BLUE_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_BLUE_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_PURPLE_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.PACKED_PURPLE_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_PURPLE_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_PURPLE_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_CYAN_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.PACKED_CYAN_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_CYAN_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_CYAN_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_LIGHT_GRAY_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.PACKED_LIGHT_GRAY_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_LIGHT_GRAY_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_LIGHT_GRAY_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_GRAY_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.PACKED_GRAY_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_GRAY_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_GRAY_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_PINK_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.PACKED_PINK_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_PINK_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_PINK_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_LIME_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.PACKED_LIME_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_LIME_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_LIME_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_YELLOW_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.PACKED_YELLOW_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_YELLOW_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_YELLOW_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_LIGHT_BLUE_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.PACKED_LIGHT_BLUE_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_LIGHT_BLUE_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_LIGHT_BLUE_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_MAGENTA_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.PACKED_MAGENTA_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_MAGENTA_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_MAGENTA_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_ORANGE_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.PACKED_ORANGE_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_ORANGE_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_ORANGE_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_WHITE_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.PACKED_WHITE_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_WHITE_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_WHITE_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_RED_SANDSTONE_BRICKS,
					BuildersPaletteModBlocks.PACKED_RED_SANDSTONE_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_RED_SANDSTONE_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_RED_SANDSTONE_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_SANDSTONE_BRICKS,
					BuildersPaletteModBlocks.PACKED_SANDSTONE_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_SANDSTONE_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_SANDSTONE_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_ANDESITE_BRICKS,
					BuildersPaletteModBlocks.PACKED_ANDESITE_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_ANDESITE_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_ANDESITE_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_GRANITE_BRICKS,
					BuildersPaletteModBlocks.PACKED_GRANITE_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_GRANITE_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_GRANITE_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_DIORITE_BRICKS,
					BuildersPaletteModBlocks.PACKED_DIORITE_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_DIORITE_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_DIORITE_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_TUFF_BRICKS,
					BuildersPaletteModBlocks.PACKED_TUFF_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_TUFF_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_TUFF_BRICKS_WALL,
					BuildersPaletteModBlocks.PACKED_CALCITE_BRICKS,
					BuildersPaletteModBlocks.PACKED_CALCITE_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PACKED_CALCITE_BRICKS_SLAB,
					BuildersPaletteModBlocks.PACKED_CALCITE_BRICKS_WALL,
					BuildersPaletteModBlocks.TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.WHITE_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.WHITE_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.WHITE_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.WHITE_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.ORANGE_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.ORANGE_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.ORANGE_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.ORANGE_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.MAGENTA_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.MAGENTA_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.MAGENTA_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.MAGENTA_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.LIGHT_BLUE_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.LIGHT_BLUE_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.LIGHT_BLUE_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.LIGHT_BLUE_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.YELLOW_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.YELLOW_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.YELLOW_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.YELLOW_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.LIME_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.LIME_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.LIME_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.LIME_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.PINK_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.PINK_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PINK_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.PINK_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.GRAY_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.GRAY_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.GRAY_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.GRAY_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.LIGHT_GRAY_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.LIGHT_GRAY_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.LIGHT_GRAY_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.LIGHT_GRAY_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.CYAN_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.CYAN_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.CYAN_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.CYAN_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.PURPLE_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.PURPLE_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.PURPLE_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.PURPLE_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.BLUE_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.BLUE_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.BLUE_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.BLUE_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.BROWN_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.BROWN_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.BROWN_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.BROWN_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.GREEN_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.GREEN_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.GREEN_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.GREEN_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.RED_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.RED_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.RED_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.RED_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.BLACK_TERRACOTTA_BRICKS,
					BuildersPaletteModBlocks.BLACK_TERRACOTTA_BRICKS_STAIRS,
					BuildersPaletteModBlocks.BLACK_TERRACOTTA_BRICKS_SLAB,
					BuildersPaletteModBlocks.BLACK_TERRACOTTA_BRICKS_WALL,
					BuildersPaletteModBlocks.GLAZED_MUD,
					BuildersPaletteModBlocks.GLAZED_MUD_STAIRS,
					BuildersPaletteModBlocks.GLAZED_MUD_SLAB,
					BuildersPaletteModBlocks.GLAZED_MUD_WALL,
					BuildersPaletteModBlocks.GLAZED_CALCITE,
					BuildersPaletteModBlocks.GLAZED_CALCITE_STAIRS,
					BuildersPaletteModBlocks.GLAZED_CALCITE_SLAB,
					BuildersPaletteModBlocks.GLAZED_CALCITE_WALL,
					BuildersPaletteModBlocks.GLAZED_TUFF,
					BuildersPaletteModBlocks.GLAZED_TUFF_STAIRS,
					BuildersPaletteModBlocks.GLAZED_TUFF_SLAB,
					BuildersPaletteModBlocks.GLAZED_TUFF_WALL,
					BuildersPaletteModBlocks.GLAZED_DIORITE,
					BuildersPaletteModBlocks.GLAZED_DIORITE_STAIRS,
					BuildersPaletteModBlocks.GLAZED_DIORITE_SLAB,
					BuildersPaletteModBlocks.GLAZED_DIORITE_WALL,
					BuildersPaletteModBlocks.GLAZED_GRANITE,
					BuildersPaletteModBlocks.GLAZED_GRANITE_STAIRS,
					BuildersPaletteModBlocks.GLAZED_GRANITE_SLAB,
					BuildersPaletteModBlocks.GLAZED_GRANITE_WALL,
					BuildersPaletteModBlocks.GLAZED_ANDESITE,
					BuildersPaletteModBlocks.GLAZED_ANDESITE_STAIRS,
					BuildersPaletteModBlocks.GLAZED_ANDESITE_SLAB,
					BuildersPaletteModBlocks.GLAZED_ANDESITE_WALL,
					BuildersPaletteModBlocks.GLAZED_SANDSTONE,
					BuildersPaletteModBlocks.GLAZED_SANDSTONE_STAIRS,
					BuildersPaletteModBlocks.GLAZED_SANDSTONE_SLAB,
					BuildersPaletteModBlocks.GLAZED_SANDSTONE_WALL,
					BuildersPaletteModBlocks.GLAZED_RED_SANDSTONE,
					BuildersPaletteModBlocks.GLAZED_RED_SANDSTONE_STAIRS,
					BuildersPaletteModBlocks.GLAZED_RED_SANDSTONE_SLAB,
					BuildersPaletteModBlocks.GLAZED_RED_SANDSTONE_WALL,
					BuildersPaletteModBlocks.GLAZED_TERRACOTTA,
					BuildersPaletteModBlocks.GLAZED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.GLAZED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.GLAZED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.GLAZED_END_STONE,
					BuildersPaletteModBlocks.GLAZED_END_STONE_STAIRS,
					BuildersPaletteModBlocks.GLAZED_END_STONE_SLAB,
					BuildersPaletteModBlocks.GLAZED_END_STONE_WALL,
					BuildersPaletteModBlocks.POLISHED_MUD,
					BuildersPaletteModBlocks.POLISHED_MUD_STAIRS,
					BuildersPaletteModBlocks.POLISHED_MUD_SLAB,
					BuildersPaletteModBlocks.POLISHED_MUD_WALL,
					BuildersPaletteModBlocks.CHISELED_MUD,
					BuildersPaletteModBlocks.CHISELED_MUD_STAIRS,
					BuildersPaletteModBlocks.CHISELED_MUD_SLAB,
					BuildersPaletteModBlocks.CHISELED_MUD_WALL,
					BuildersPaletteModBlocks.POLISHED_CALCITE,
					BuildersPaletteModBlocks.POLISHED_CALCITE_STAIRS,
					BuildersPaletteModBlocks.POLISHED_CALCITE_SLAB,
					BuildersPaletteModBlocks.POLISHED_CALCITE_WALL,
					BuildersPaletteModBlocks.CHISELED_CALCITE,
					BuildersPaletteModBlocks.CHISELED_CALCITE_STAIRS,
					BuildersPaletteModBlocks.CHISELED_CALCITE_SLAB,
					BuildersPaletteModBlocks.CHISELED_CALCITE_WALL,
					BuildersPaletteModBlocks.POLISHED_TUFF,
					BuildersPaletteModBlocks.POLISHED_TUFF_STAIRS,
					BuildersPaletteModBlocks.POLISHED_TUFF_SLAB,
					BuildersPaletteModBlocks.POLISHED_TUFF_WALL,
					BuildersPaletteModBlocks.CHISELED_TUFF,
					BuildersPaletteModBlocks.CHISELED_TUFF_STAIRS,
					BuildersPaletteModBlocks.CHISELED_TUFF_SLAB,
					BuildersPaletteModBlocks.CHISELED_TUFF_WALL,
					BuildersPaletteModBlocks.POLISHED_DIORITE,
					BuildersPaletteModBlocks.POLISHED_DIORITE_STAIRS,
					BuildersPaletteModBlocks.POLISHED_DIORITE_SLAB,
					BuildersPaletteModBlocks.POLISHED_DIORITE_WALL,
					BuildersPaletteModBlocks.CHISELED_DIORITE,
					BuildersPaletteModBlocks.CHISELED_DIORITE_STAIRS,
					BuildersPaletteModBlocks.CHISELED_DIORITE_SLAB,
					BuildersPaletteModBlocks.CHISELED_DIORITE_WALL,
					BuildersPaletteModBlocks.POLISHED_GRANITE,
					BuildersPaletteModBlocks.POLISHED_GRANITE_STAIRS,
					BuildersPaletteModBlocks.POLISHED_GRANITE_SLAB,
					BuildersPaletteModBlocks.POLISHED_GRANITE_WALL,
					BuildersPaletteModBlocks.CHISELED_GRANITE,
					BuildersPaletteModBlocks.CHISELED_GRANITE_STAIRS,
					BuildersPaletteModBlocks.CHISELED_GRANITE_SLAB,
					BuildersPaletteModBlocks.CHISELED_GRANITE_WALL,
					BuildersPaletteModBlocks.POLISHED_ANDESITE,
					BuildersPaletteModBlocks.POLISHED_ANDESITE_STAIRS,
					BuildersPaletteModBlocks.POLISHED_ANDESITE_SLAB,
					BuildersPaletteModBlocks.POLISHED_ANDESITE_WALL,
					BuildersPaletteModBlocks.CHISELED_ANDESITE,
					BuildersPaletteModBlocks.CHISELED_ANDESITE_STAIRS,
					BuildersPaletteModBlocks.CHISELED_ANDESITE_SLAB,
					BuildersPaletteModBlocks.CHISELED_ANDESITE_WALL,
					BuildersPaletteModBlocks.POLISHED_SANDSTONE,
					BuildersPaletteModBlocks.POLISHED_SANDSTONE_STAIRS,
					BuildersPaletteModBlocks.POLISHED_SANDSTONE_SLAB,
					BuildersPaletteModBlocks.POLISHED_SANDSTONE_WALL,
					BuildersPaletteModBlocks.CHISELED_SANDSTONE_STAIRS,
					BuildersPaletteModBlocks.CHISELED_SANDSTONE_SLAB,
					BuildersPaletteModBlocks.CHISELED_SANDSTONE_WALL,
					BuildersPaletteModBlocks.POLISHED_RED_SANDSTONE,
					BuildersPaletteModBlocks.POLISHED_RED_SANDSTONE_STAIRS,
					BuildersPaletteModBlocks.POLISHED_RED_SANDSTONE_SLAB,
					BuildersPaletteModBlocks.POLISHED_RED_SANDSTONE_WALL,
					BuildersPaletteModBlocks.CHISELED_RED_SANDSTONE_STAIRS,
					BuildersPaletteModBlocks.CHISELED_RED_SANDSTONE_SLAB,
					BuildersPaletteModBlocks.CHISELED_RED_SANDSTONE_WALL,
					BuildersPaletteModBlocks.POLISHED_TERRACOTTA,
					BuildersPaletteModBlocks.POLISHED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.POLISHED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.POLISHED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.CHISELED_TERRACOTTA,
					BuildersPaletteModBlocks.CHISELED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.CHISELED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.CHISELED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.POLISHED_WHITE_TERRACOTTA,
					BuildersPaletteModBlocks.POLISHED_WHITE_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.POLISHED_WHITE_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.POLISHED_WHITE_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.CHISELED_WHITE_TERRACOTTA,
					BuildersPaletteModBlocks.CHISELED_WHITE_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.CHISELED_WHITE_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.CHISELED_WHITE_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.POLISHED_ORANGE_TERRACOTTA,
					BuildersPaletteModBlocks.POLISHED_ORANGE_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.POLISHED_ORANGE_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.POLISHED_ORANGE_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.CHISELED_ORANGE_TERRACOTTA,
					BuildersPaletteModBlocks.CHISELED_ORANGE_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.CHISELED_ORANGE_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.CHISELED_ORANGE_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.POLISHED_MAGENTA_TERRACOTTA,
					BuildersPaletteModBlocks.POLISHED_MAGENTA_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.POLISHED_MAGENTA_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.POLISHED_MAGENTA_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.CHISELED_MAGENTA_TERRACOTTA,
					BuildersPaletteModBlocks.CHISELED_MAGENTA_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.CHISELED_MAGENTA_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.CHISELED_MAGENTA_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.POLISHED_LIGHT_BLUE_TERRACOTTA,
					BuildersPaletteModBlocks.POLISHED_LIGHT_BLUE_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.POLISHED_LIGHT_BLUE_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.POLISHED_LIGHT_BLUE_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.CHISELED_LIGHT_BLUE_TERRACOTTA,
					BuildersPaletteModBlocks.CHISELED_LIGHT_BLUE_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.CHISELED_LIGHT_BLUE_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.CHISELED_LIGHT_BLUE_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.POLISHED_YELLOW_TERRACOTTA,
					BuildersPaletteModBlocks.POLISHED_YELLOW_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.POLISHED_YELLOW_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.POLISHED_YELLOW_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.CHISELED_YELLOW_TERRACOTTA,
					BuildersPaletteModBlocks.CHISELED_YELLOW_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.CHISELED_YELLOW_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.CHISELED_YELLOW_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.POLISHED_LIME_TERRACOTTA,
					BuildersPaletteModBlocks.POLISHED_LIME_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.POLISHED_LIME_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.POLISHED_LIME_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.CHISELED_LIME_TERRACOTTA,
					BuildersPaletteModBlocks.CHISELED_LIME_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.CHISELED_LIME_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.CHISELED_LIME_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.POLISHED_PINK_TERRACOTTA,
					BuildersPaletteModBlocks.POLISHED_PINK_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.POLISHED_PINK_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.POLISHED_PINK_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.CHISELED_PINK_TERRACOTTA,
					BuildersPaletteModBlocks.CHISELED_PINK_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.CHISELED_PINK_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.CHISELED_PINK_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.POLISHED_GRAY_TERRACOTTA,
					BuildersPaletteModBlocks.POLISHED_GRAY_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.POLISHED_GRAY_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.POLISHED_GRAY_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.CHISELED_GRAY_TERRACOTTA,
					BuildersPaletteModBlocks.CHISELED_GRAY_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.CHISELED_GRAY_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.CHISELED_GRAY_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.POLISHED_LIGHT_GRAY_TERRACOTTA,
					BuildersPaletteModBlocks.POLISHED_LIGHT_GRAY_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.POLISHED_LIGHT_GRAY_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.POLISHED_LIGHT_GRAY_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.CHISELED_LIGHT_GRAY_TERRACOTTA,
					BuildersPaletteModBlocks.CHISELED_LIGHT_GRAY_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.CHISELED_LIGHT_GRAY_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.CHISELED_LIGHT_GRAY_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.POLISHED_CYAN_TERRACOTTA,
					BuildersPaletteModBlocks.POLISHED_CYAN_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.POLISHED_CYAN_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.POLISHED_CYAN_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.CHISELED_CYAN_TERRACOTTA,
					BuildersPaletteModBlocks.CHISELED_CYAN_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.CHISELED_CYAN_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.CHISELED_CYAN_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.POLISHED_PURPLE_TERRACOTTA,
					BuildersPaletteModBlocks.POLISHED_PURPLE_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.POLISHED_PURPLE_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.POLISHED_PURPLE_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.CHISELED_PURPLE_TERRACOTTA,
					BuildersPaletteModBlocks.CHISELED_PURPLE_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.CHISELED_PURPLE_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.CHISELED_PURPLE_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.POLISHED_BLUE_TERRACOTTA,
					BuildersPaletteModBlocks.POLISHED_BLUE_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.POLISHED_BLUE_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.POLISHED_BLUE_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.CHISELED_BLUE_TERRACOTTA,
					BuildersPaletteModBlocks.CHISELED_BLUE_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.CHISELED_BLUE_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.CHISELED_BLUE_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.POLISHED_BROWN_TERRACOTTA,
					BuildersPaletteModBlocks.POLISHED_BROWN_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.POLISHED_BROWN_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.POLISHED_BROWN_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.CHISELED_BROWN_TERRACOTTA,
					BuildersPaletteModBlocks.CHISELED_BROWN_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.CHISELED_BROWN_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.CHISELED_BROWN_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.POLISHED_GREEN_TERRACOTTA,
					BuildersPaletteModBlocks.POLISHED_GREEN_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.POLISHED_GREEN_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.POLISHED_GREEN_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.CHISELED_GREEN_TERRACOTTA,
					BuildersPaletteModBlocks.CHISELED_GREEN_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.CHISELED_GREEN_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.CHISELED_GREEN_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.POLISHED_RED_TERRACOTTA,
					BuildersPaletteModBlocks.POLISHED_RED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.POLISHED_RED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.POLISHED_RED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.CHISELED_RED_TERRACOTTA,
					BuildersPaletteModBlocks.CHISELED_RED_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.CHISELED_RED_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.CHISELED_RED_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.POLISHED_BLACK_TERRACOTTA,
					BuildersPaletteModBlocks.POLISHED_BLACK_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.POLISHED_BLACK_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.POLISHED_BLACK_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.CHISELED_BLACK_TERRACOTTA,
					BuildersPaletteModBlocks.CHISELED_BLACK_TERRACOTTA_STAIRS,
					BuildersPaletteModBlocks.CHISELED_BLACK_TERRACOTTA_SLAB,
					BuildersPaletteModBlocks.CHISELED_BLACK_TERRACOTTA_WALL,
					BuildersPaletteModBlocks.POLISHED_END_STONE,
					BuildersPaletteModBlocks.POLISHED_END_STONE_STAIRS,
					BuildersPaletteModBlocks.POLISHED_END_STONE_SLAB,
					BuildersPaletteModBlocks.POLISHED_END_STONE_WALL,
					BuildersPaletteModBlocks.CHISELED_END_STONE,
					BuildersPaletteModBlocks.CHISELED_END_STONE_STAIRS,
					BuildersPaletteModBlocks.CHISELED_END_STONE_SLAB,
					BuildersPaletteModBlocks.CHISELED_END_STONE_WALL
				);
				acceptBlocks(tabData,
					BuildersPaletteModBlocks.MUD_PILLAR,
					BuildersPaletteModBlocks.CALCITE_PILLAR,
					BuildersPaletteModBlocks.TUFF_PILLAR,
					BuildersPaletteModBlocks.DIORITE_PILLAR,
					BuildersPaletteModBlocks.GRANITE_PILLAR,
					BuildersPaletteModBlocks.ANDESITE_PILLAR,
					BuildersPaletteModBlocks.SANDSTONE_PILLAR,
					BuildersPaletteModBlocks.RED_SANDSTONE_PILLAR,
					BuildersPaletteModBlocks.TERRACOTTA_PILLAR,
					BuildersPaletteModBlocks.WHITE_TERRACOTTA_PILLAR,
					BuildersPaletteModBlocks.ORANGE_TERRACOTTA_PILLAR,
					BuildersPaletteModBlocks.MAGENTA_TERRACOTTA_PILLAR,
					BuildersPaletteModBlocks.LIGHT_BLUE_TERRACOTTA_PILLAR,
					BuildersPaletteModBlocks.YELLOW_TERRACOTTA_PILLAR,
					BuildersPaletteModBlocks.LIME_TERRACOTTA_PILLAR,
					BuildersPaletteModBlocks.PINK_TERRACOTTA_PILLAR,
					BuildersPaletteModBlocks.GRAY_TERRACOTTA_PILLAR,
					BuildersPaletteModBlocks.LIGHT_GRAY_TERRACOTTA_PILLAR,
					BuildersPaletteModBlocks.CYAN_TERRACOTTA_PILLAR,
					BuildersPaletteModBlocks.PURPLE_TERRACOTTA_PILLAR,
					BuildersPaletteModBlocks.BLUE_TERRACOTTA_PILLAR,
					BuildersPaletteModBlocks.BROWN_TERRACOTTA_PILLAR,
					BuildersPaletteModBlocks.GREEN_TERRACOTTA_PILLAR,
					BuildersPaletteModBlocks.RED_TERRACOTTA_PILLAR,
					BuildersPaletteModBlocks.BLACK_TERRACOTTA_PILLAR,
					BuildersPaletteModBlocks.END_STONE_PILLAR
				);
				GeneratedBlockFamilies.addToTab(tabData);
				GeneratedPastelConcrete.addToTab(tabData);
			}).build());

	@SafeVarargs
	private static void acceptBlocks(CreativeModeTab.Output tabData, RegistryObject<Block>... blocks) {
		for (RegistryObject<Block> block : blocks) {
			tabData.accept(block.get().asItem());
		}
	}
}
