package com.cookiecraftmods.builderspalette.init;

import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.RotatedPillarBlock;
import net.minecraft.world.level.block.SlabBlock;
import net.minecraft.world.level.block.StairBlock;
import net.minecraft.world.level.block.WallBlock;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.level.block.SoundType;

import java.util.ArrayList;
import java.util.List;

/** Generated by tools/generate_pastel_concrete.py. */
public final class GeneratedPastelConcrete {
	private static final List<RegistryObject<Block>> BLOCKS = new ArrayList<>();
	private static boolean blocksRegistered;
	private static boolean itemsRegistered;

	private GeneratedPastelConcrete() {
	}

	public static void registerBlocks() {
		if (blocksRegistered) return;
		blocksRegistered = true;
		registerFamily("pastel_rose_smooth_concrete", false);
		registerFamily("pastel_rose_concrete_bricks", false);
		registerFamily("pastel_rose_packed_concrete_bricks", false);
		registerFamily("pastel_rose_concrete_pillar", true);
		registerFamily("pastel_coral_smooth_concrete", false);
		registerFamily("pastel_coral_concrete_bricks", false);
		registerFamily("pastel_coral_packed_concrete_bricks", false);
		registerFamily("pastel_coral_concrete_pillar", true);
		registerFamily("pastel_peach_smooth_concrete", false);
		registerFamily("pastel_peach_concrete_bricks", false);
		registerFamily("pastel_peach_packed_concrete_bricks", false);
		registerFamily("pastel_peach_concrete_pillar", true);
		registerFamily("pastel_butter_smooth_concrete", false);
		registerFamily("pastel_butter_concrete_bricks", false);
		registerFamily("pastel_butter_packed_concrete_bricks", false);
		registerFamily("pastel_butter_concrete_pillar", true);
		registerFamily("pastel_sage_smooth_concrete", false);
		registerFamily("pastel_sage_concrete_bricks", false);
		registerFamily("pastel_sage_packed_concrete_bricks", false);
		registerFamily("pastel_sage_concrete_pillar", true);
		registerFamily("pastel_mint_smooth_concrete", false);
		registerFamily("pastel_mint_concrete_bricks", false);
		registerFamily("pastel_mint_packed_concrete_bricks", false);
		registerFamily("pastel_mint_concrete_pillar", true);
		registerFamily("pastel_aqua_smooth_concrete", false);
		registerFamily("pastel_aqua_concrete_bricks", false);
		registerFamily("pastel_aqua_packed_concrete_bricks", false);
		registerFamily("pastel_aqua_concrete_pillar", true);
		registerFamily("pastel_sky_smooth_concrete", false);
		registerFamily("pastel_sky_concrete_bricks", false);
		registerFamily("pastel_sky_packed_concrete_bricks", false);
		registerFamily("pastel_sky_concrete_pillar", true);
		registerFamily("pastel_periwinkle_smooth_concrete", false);
		registerFamily("pastel_periwinkle_concrete_bricks", false);
		registerFamily("pastel_periwinkle_packed_concrete_bricks", false);
		registerFamily("pastel_periwinkle_concrete_pillar", true);
		registerFamily("pastel_lavender_smooth_concrete", false);
		registerFamily("pastel_lavender_concrete_bricks", false);
		registerFamily("pastel_lavender_packed_concrete_bricks", false);
		registerFamily("pastel_lavender_concrete_pillar", true);
	}

	public static void registerItems() {
		if (itemsRegistered) return;
		if (!blocksRegistered) throw new IllegalStateException("Pastel concrete blocks must be registered before their items");
		itemsRegistered = true;
		for (RegistryObject<Block> block : BLOCKS) {
			RegistryObject.register(BuiltInRegistries.ITEM, block.getId().getPath(),
					() -> new BlockItem(block.get(), new Item.Properties()));
		}
	}

	public static void addToTab(CreativeModeTab.Output entries) {
		for (RegistryObject<Block> block : BLOCKS) entries.accept(block.get().asItem());
	}

	private static void registerFamily(String name, boolean pillar) {
		RegistryObject<Block> base = pillar
				? register(name, () -> new RotatedPillarBlock(settings()))
				: register(name, () -> new Block(settings()));
		register(name + "_stairs", () -> new StairBlock(base.get().defaultBlockState(), BlockBehaviour.Properties.ofFullCopy(base.get())));
		register(name + "_slab", () -> new SlabBlock(BlockBehaviour.Properties.ofFullCopy(base.get())));
		register(name + "_wall", () -> new WallBlock(BlockBehaviour.Properties.ofFullCopy(base.get())));
	}

	private static BlockBehaviour.Properties settings() {
		return BlockBehaviour.Properties.of().sound(SoundType.STONE).strength(1.8f, 6.0f).requiresCorrectToolForDrops();
	}

	private static RegistryObject<Block> register(String name, java.util.function.Supplier<? extends Block> supplier) {
		RegistryObject<Block> block = RegistryObject.register(BuiltInRegistries.BLOCK, name, supplier);
		BLOCKS.add(block);
		return block;
	}
}
