package com.cookiecraftmods.builderspalette.init;

import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.PillarBlock;
import net.minecraft.block.SlabBlock;
import net.minecraft.block.StairsBlock;
import net.minecraft.block.WallBlock;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.registry.Registries;
import net.minecraft.sound.BlockSoundGroup;

import java.util.ArrayList;
import java.util.List;

/** Generated by tools/generate_pastel_concrete.py. */
public final class GeneratedPastelConcrete {
	private static final List<RegistryObject<Block>> BLOCKS = new ArrayList<>();
	private static boolean blocksRegistered;
	private static boolean itemsRegistered;

	private GeneratedPastelConcrete() {
	}

	public static void registerBlocks() {
		if (blocksRegistered) return;
		blocksRegistered = true;
		registerFamily("pastel_rose_smooth_concrete", false);
		registerFamily("pastel_rose_concrete_bricks", false);
		registerFamily("pastel_rose_packed_concrete_bricks", false);
		registerFamily("pastel_rose_concrete_pillar", true);
		registerFamily("pastel_coral_smooth_concrete", false);
		registerFamily("pastel_coral_concrete_bricks", false);
		registerFamily("pastel_coral_packed_concrete_bricks", false);
		registerFamily("pastel_coral_concrete_pillar", true);
		registerFamily("pastel_peach_smooth_concrete", false);
		registerFamily("pastel_peach_concrete_bricks", false);
		registerFamily("pastel_peach_packed_concrete_bricks", false);
		registerFamily("pastel_peach_concrete_pillar", true);
		registerFamily("pastel_butter_smooth_concrete", false);
		registerFamily("pastel_butter_concrete_bricks", false);
		registerFamily("pastel_butter_packed_concrete_bricks", false);
		registerFamily("pastel_butter_concrete_pillar", true);
		registerFamily("pastel_sage_smooth_concrete", false);
		registerFamily("pastel_sage_concrete_bricks", false);
		registerFamily("pastel_sage_packed_concrete_bricks", false);
		registerFamily("pastel_sage_concrete_pillar", true);
		registerFamily("pastel_mint_smooth_concrete", false);
		registerFamily("pastel_mint_concrete_bricks", false);
		registerFamily("pastel_mint_packed_concrete_bricks", false);
		registerFamily("pastel_mint_concrete_pillar", true);
		registerFamily("pastel_aqua_smooth_concrete", false);
		registerFamily("pastel_aqua_concrete_bricks", false);
		registerFamily("pastel_aqua_packed_concrete_bricks", false);
		registerFamily("pastel_aqua_concrete_pillar", true);
		registerFamily("pastel_sky_smooth_concrete", false);
		registerFamily("pastel_sky_concrete_bricks", false);
		registerFamily("pastel_sky_packed_concrete_bricks", false);
		registerFamily("pastel_sky_concrete_pillar", true);
		registerFamily("pastel_periwinkle_smooth_concrete", false);
		registerFamily("pastel_periwinkle_concrete_bricks", false);
		registerFamily("pastel_periwinkle_packed_concrete_bricks", false);
		registerFamily("pastel_periwinkle_concrete_pillar", true);
		registerFamily("pastel_lavender_smooth_concrete", false);
		registerFamily("pastel_lavender_concrete_bricks", false);
		registerFamily("pastel_lavender_packed_concrete_bricks", false);
		registerFamily("pastel_lavender_concrete_pillar", true);
	}

	public static void registerItems() {
		if (itemsRegistered) return;
		if (!blocksRegistered) throw new IllegalStateException("Pastel concrete blocks must be registered before their items");
		itemsRegistered = true;
		for (RegistryObject<Block> block : BLOCKS) {
			RegistryObject.register(Registries.ITEM, block.getId().getPath(),
					() -> new BlockItem(block.get(), new Item.Settings()));
		}
	}

	public static void addToTab(ItemGroup.Entries entries) {
		for (RegistryObject<Block> block : BLOCKS) entries.add(block.get().asItem());
	}

	private static void registerFamily(String name, boolean pillar) {
		RegistryObject<Block> base = pillar
				? register(name, () -> new PillarBlock(settings()))
				: register(name, () -> new Block(settings()));
		register(name + "_stairs", () -> new StairsBlock(base.get().getDefaultState(), AbstractBlock.Settings.copy(base.get())));
		register(name + "_slab", () -> new SlabBlock(AbstractBlock.Settings.copy(base.get())));
		register(name + "_wall", () -> new WallBlock(AbstractBlock.Settings.copy(base.get())));
	}

	private static AbstractBlock.Settings settings() {
		return AbstractBlock.Settings.create().sounds(BlockSoundGroup.STONE).strength(1.8f, 6.0f).requiresTool();
	}

	private static RegistryObject<Block> register(String name, java.util.function.Supplier<? extends Block> supplier) {
		RegistryObject<Block> block = RegistryObject.register(Registries.BLOCK, name, supplier);
		BLOCKS.add(block);
		return block;
	}
}
